src/account/urls.py
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    path('smoke/', views.smoke, name='smoke'),
    path('profile/<int:pk>/', views.MyProfile.as_view(), name='my-profile'),
    path('contact-us/', views.ContactUs.as_view(), name='contact-us'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uuid:activation_code>/', views.Activate.as_view(), name='activate'),
    path('rates/', views.RatesList.as_view(), name='latest-rates'),
    path('latest-rates/', views.LatestRates.as_view(), name='latest-rates2'),
]

src/currency/urls.py
from django.urls import path

from currency import views

app_name = 'currency'

urlpatterns = [
    path('download/rates/', views.RateCSV.as_view(), name='download-rates'),
]

src/currency_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# from currency_exchange import settings WRONG!
from django.conf import settings

API_PREFIX = 'api/v1'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),

    path('account/', include('account.urls')),
    path('currency/', include('currency.urls')),

    # API
    path(f'{API_PREFIX}/currency/', include('currency.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

# SWAGGER
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='DOCS')

urlpatterns.append(path(f'{API_PREFIX}/docs/', schema_view))

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg2NDU5MzQxLCJqdGkiOiIxZTJjNjAxMjBmNjc0MmFmYmIwNmFkYjBkYTJkODc1OCIsInVzZXJfaWQiOjh9.PScH_ZKujjlF8zJyGWGVC7_DjxVscm843Aog2YW9838
# Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg2NDU5MzQxLCJqdGkiOiIxZTJjNjAxMjBmNjc0MmFmYmIwNmFkYjBkYTJkODc1OCIsInVzZXJfaWQiOjh9.PScH_ZKujjlF8zJyGWGVC7_DjxVscm843Aog2YW9838

src/account/models.py
from uuid import uuid4
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser

from account.tasks import send_activation_code_async


def avatar_path(instance, filename: str) -> str:
    # ext = filename.split('.')[-1]
    # f = str(uuid4())
    # filename = f'{f}.{ext}'
    # return '/'.join(['hello', filename])

    return '/'.join(['avatar', str(instance.id), str(uuid4()), filename])


class User(AbstractUser):
    avatar = models.ImageField(upload_to=avatar_path,
                               null=True, blank=True,
                               default=None)

    def __str__(self):
        return str(self.__dict__)


class Contact(models.Model):
    email = models.EmailField()
    title = models.CharField(max_length=256)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class ActivationCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='activation_codes')
    created = models.DateTimeField(auto_now_add=True)
    # code = models.CharField(max_length=128)
    code = models.UUIDField(default=uuid4, editable=False, unique=True)
    is_activated = models.BooleanField(default=False)

    @property
    def is_expired(self):
        now = datetime.now()
        diff = now - self.created
        return diff.days > 7

    def send_activation_code(self):
        send_activation_code_async.delay(self.user.email, self.code)

    # def save(self, *args, **kwargs):
    #     self.code = ... # GENERTE CODE
    #     super().save(*args, **kwargs)

src/currency/models.py
from django.db import models

from currency import model_choices as mch


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(choices=mch.CURRENCY_CHOICES)
    buy = models.DecimalField(max_digits=4, decimal_places=2)
    sale = models.DecimalField(max_digits=4, decimal_places=2)
    source = models.PositiveSmallIntegerField(choices=mch.SOURCE_CHOICES)

    def __str__(self):
        return f'{self.created} {self.get_currency_display()} {self.buy} {self.sale}'

    def save(self, *args, **kwargs):
        from django.core.cache import cache

        if not self.id:
            from currency.utils import generate_rate_cache_key
            cache_key = generate_rate_cache_key(self.source, self.currency)
            cache.delete(cache_key)

        super().save(*args, **kwargs)

    @classmethod
    def create_random_rate(cls):
        import random
        cls.objects.create(
            currency=random.choice([1, 2]),
            buy=random.randint(20, 30),
            sale=random.randint(20, 30),
            source=random.choice([1, 2]),
        )

src/account/forms.py
from django import forms

from account.models import User


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    # email = forms.EmailField

    class Meta:
        model = User
        fields = ('email', 'username', 'password', 'password2')

    def clean(self):
        cleaned_data = super().clean()
        if not self.errors:
            if cleaned_data['password'] != cleaned_data['password2']:
                raise forms.ValidationError('Passwords do not match!')
        return cleaned_data

    def save(self, commit=True):

        user = super().save(commit=False)  # no save to database
        user.set_password(self.cleaned_data['password'])  # password should be hashed!
        user.is_active = False   # user cannot login
        user.save()

        activation_code = user.activation_codes.create()
        activation_code.send_activation_code()
        return user

src/account/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, View, ListView, TemplateView

from account.forms import SignUpForm
from account.models import User, Contact, ActivationCode
from account.tasks import send_tel_message
from currency.models import Rate


def smoke(request):
    return HttpResponse('smoke')


# def my_profile(request):
#     return render(request, 'my_profile.html')

class MyProfile(UpdateView):
    template_name = 'my_profile.html'
    queryset = User.objects.filter(is_active=True)
    fields = ('email', )
    success_url = reverse_lazy('index')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(id=self.request.user.id)


class ContactUs(CreateView):
    template_name = 'my_profile.html'
    queryset = Contact.objects.all()
    fields = ('email', 'title', 'body')
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        response = super().form_valid(form)
        #### send email
        print(self.object)
        # send_email_async.delay()
        return response


class SignUpView(CreateView):
    template_name = 'signup.html'
    queryset = User.objects.all()
    success_url = reverse_lazy('index')
    form_class = SignUpForm


class Activate(View):
    def get(self, request, activation_code):
        ac = get_object_or_404(
            ActivationCode.objects.select_related('user'),
            code=activation_code, is_activated=False,
        )

        if ac.is_expired:
            raise Http404

        ac.is_activated = True
        ac.save(update_fields=['is_activated'])

        user = ac.user
        user.is_active = True
        user.save(update_fields=['is_active'])

        ### SEND MESSAGE
        # send_tel_message()
        send_tel_message.delay()

        return redirect('index')


from django_filters.views import FilterView
from account.filters import RateFilter


class RatesList(FilterView):
    filterset_class = RateFilter
    queryset = Rate.objects.all()
    template_name = 'rates.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        from urllib.parse import urlencode
        context = super().get_context_data(*args, **kwargs)

        query_params = dict(self.request.GET.items())
        if 'page' in query_params:
            del query_params['page']
        context['query_params'] = urlencode(query_params)

        return context

    # @property
    # def template_name(self):

    # @property
    # def paginate_by(self):
    #     paginate = int(self.request.GET.get('paginate-by'))
    #     return paginate


class LatestRates(TemplateView):
    template_name = 'latest-rates.html'

    def get_context_data(self, **kwargs):
        from currency import model_choices as mch
        from django.core.cache import cache

        context = super().get_context_data(**kwargs)
        # rates = {
        #     'privatBank': [Rate.objects.filter(source=mch.SR_PRIVAT, currency=mch.CURR_USD).last(),
        #                    Rate.objects.filter(source=mch.SR_PRIVAT, currency=mch.CURR_EUR).last()],
        #     'MonoBank': [Rate.objects.filter(source=mch.SR_MONO, currency=mch.CURR_USD).last(),
        #                    Rate.objects.filter(source=mch.SR_MONO, currency=mch.CURR_EUR).last()]
        # }

        rates = []
        for bank in mch.SOURCE_CHOICES:
            source = bank[0]
            for curr in mch.CURRENCY_CHOICES:
                currency = curr[0]
                from currency.utils import generate_rate_cache_key
                cache_key = generate_rate_cache_key(source, currency)

                rate = cache.get(cache_key)

                if rate is None:
                    rate = Rate.objects.filter(source=source, currency=currency).order_by('created').last()
                    if rate:
                        rate_dict = {
                            'currency': rate.currency,
                            'source': rate.source,
                            'sale': rate.sale,
                            'buy': rate.buy,
                            'created': rate.created,
                        }
                        rates.append(rate_dict)
                        cache.set(cache_key, rate_dict, 60 * 15)  # 15 minutes
                        # cache.set(cache_key, rate_dict, 5)  # 5 seconds
                else:
                    rates.append(rate)

        context['rates'] = rates
        # Rate.objects.filter(source=mch.SR_PRIVAT, currency=mch.CURR_USD).order_by('-created')[0]
        return context

'''
source PrivatBank - latest USD, latest UER
source MonoBank - latest USD, latest UER
'''

src/account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock title %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'ln/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{% static 'ln/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'ln/css/resume.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
      <span class="d-block d-lg-none">{{ request.user.get_full_name }}</span>
      {% if request.user.is_authenticated and request.user.avatar %}
      <span class="d-none d-lg-block">
        <img class="img-fluid img-profile rounded-circle mx-auto mb-2"
             src="{{ request.user.avatar.url }}" alt="">
      </span>
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'account:latest-rates' %}">Rates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'account:latest-rates2' %}">Latest Rates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#education">Education</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger"
             href="{% url 'currency:download-rates' %}">Download Rates</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:contact-us' %}">Contact Us</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:my-profile' request.user.id %}">My profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:signup' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container-fluid p-0">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'ln/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'ln/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'ln/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'ln/js/resume.min.js' %}"></script>

</body>

</html>

src/account/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock title %}

{% block content %}
<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="about">
    <div class="w-100">
        <h1 class="mb-0">Clarence
            <span class="text-primary">Taylor</span>
        </h1>
        <div class="subheading mb-5">3542 Berry Street · Cheyenne Wells, CO 80810 · (317) 585-8468 ·
            <a href="mailto:name@email.com">name@email.com</a>
        </div>
        <p class="lead mb-5">I am experienced in leveraging agile frameworks to provide a robust synopsis for high level
            overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall
            value proposition.</p>
        <div class="social-icons">
            <a href="#">
                <i class="fab fa-linkedin-in"></i>
            </a>
            <a href="#">
                <i class="fab fa-github"></i>
            </a>
            <a href="#">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
                <i class="fab fa-facebook-f"></i>
            </a>
        </div>
    </div>
</section>

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex justify-content-center" id="experience">
    <div class="w-100">
        <h2 class="mb-5">Experience</h2>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Senior Web Developer</h3>
                <div class="subheading mb-3">Intelitec Solutions</div>
                <p>Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day,
                    going forward, a new normal that has evolved from generation X is on the runway heading towards a
                    streamlined cloud solution. User generated content in real-time will have multiple touchpoints for
                    offshoring.</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">March 2013 - Present</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Web Developer</h3>
                <div class="subheading mb-3">Intelitec Solutions</div>
                <p>Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override
                    the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the
                    information highway will close the loop on focusing solely on the bottom line.</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">December 2011 - March 2013</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Junior Web Designer</h3>
                <div class="subheading mb-3">Shout! Media Productions</div>
                <p>Podcasting operational change management inside of workflows to establish a framework. Taking
                    seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball
                    while performing a deep dive on the start-up mentality to derive convergence on cross-platform
                    integration.</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">July 2010 - December 2011</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between">
            <div class="resume-content">
                <h3 class="mb-0">Web Design Intern</h3>
                <div class="subheading mb-3">Shout! Media Productions</div>
                <p>Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate
                    B2C users after installed base benefits. Dramatically visualize customer directed convergence
                    without revolutionary ROI.</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">September 2008 - June 2010</span>
            </div>
        </div>

    </div>

</section>

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="education">
    <div class="w-100">
        <h2 class="mb-5">Education</h2>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">University of Colorado Boulder</h3>
                <div class="subheading mb-3">Bachelor of Science</div>
                <div>Computer Science - Web Development Track</div>
                <p>GPA: 3.23</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">August 2006 - May 2010</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between">
            <div class="resume-content">
                <h3 class="mb-0">James Buchanan High School</h3>
                <div class="subheading mb-3">Technology Magnet Program</div>
                <p>GPA: 3.56</p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">August 2002 - May 2006</span>
            </div>
        </div>

    </div>
</section>

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="skills">
    <div class="w-100">
        <h2 class="mb-5">Skills</h2>

        <div class="subheading mb-3">Programming Languages &amp; Tools</div>
        <ul class="list-inline dev-icons">
            <li class="list-inline-item">
                <i class="fab fa-html5"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-css3-alt"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-js-square"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-angular"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-react"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-node-js"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-sass"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-less"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-wordpress"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-gulp"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-grunt"></i>
            </li>
            <li class="list-inline-item">
                <i class="fab fa-npm"></i>
            </li>
        </ul>

        <div class="subheading mb-3">Workflow</div>
        <ul class="fa-ul mb-0">
            <li>
                <i class="fa-li fa fa-check"></i>
                Mobile-First, Responsive Design
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Cross Browser Testing &amp; Debugging
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Cross Functional Teams
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Agile Development &amp; Scrum
            </li>
        </ul>
    </div>
</section>

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="interests">
    <div class="w-100">
        <h2 class="mb-5">Interests</h2>
        <p>Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skier
            and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing,
            and kayaking.</p>
        <p class="mb-0">When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows,
            I am an aspiring chef, and I spend a large amount of my free time exploring the latest technology
            advancements in the front-end web development world.</p>
    </div>
</section>

<hr class="m-0">

<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="awards">
    <div class="w-100">
        <h2 class="mb-5">Awards &amp; Certifications</h2>
        <ul class="fa-ul mb-0">
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                Google Analytics Certified Developer
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                Mobile Web Specialist - Google Certification
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                1<sup>st</sup>
                Place - University of Colorado Boulder - Emerging Tech Competition 2009
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                1<sup>st</sup>
                Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                2<sup>nd</sup>
                Place - University of Colorado Boulder - Emerging Tech Competition 2008
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                1<sup>st</sup>
                Place - James Buchanan High School - Hackathon 2006
            </li>
            <li>
                <i class="fa-li fa fa-trophy text-warning"></i>
                3<sup>rd</sup>
                Place - James Buchanan High School - Hackathon 2005
            </li>
        </ul>
    </div>
</section>
{% endblock content %}

src/account/templates/latest-rates.html
{% extends 'base.html' %}

{% block title %}Latest Rates{% endblock title %}

{% block content %}
    {% for rate in rates %}
        <p>{{ rate }}</p>
    {% endfor %}
{% endblock content %}

src/account/templates/my_profile.html
{% extends 'base.html' %}

{% block title %}My profile{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}

src/account/templates/rates.html
{% extends 'base.html' %}

{% block title %}My profile{% endblock title %}

{% block content %}

    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span> Search
        </button>
    </form>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Created</th>
            <th>Currency</th>
            <th>Buy</th>
            <th>Sale</th>
            <th>Source</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.created }}</td>
                <td>{{ obj.get_currency_display }}</td>
                <td>{{ obj.buy }}</td>
                <td>{{ obj.sale }}</td>
                <td>{{ obj.get_source_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include 'includes/pagination.html' %}

{% endblock content %}

src/account/templates/signup.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}